remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: Khoa D Pham
logo: /assets/img/My Portrait.jpg
description:
  - ğŸ“ Los Angeles, CA
  -
  - ğŸ“ I'm a Master's student majoring in Data Science and Business Analytics.
  - ğŸ“Š I'm passionate about using data to drive insights and support decision-making.
  - ğŸ“ˆ My experiences in finance, healthcare refined my data analysis and research skills.
  - ğŸ§‘â€ğŸ’» Skilled in Python, SQL, R, Tableau but I'm also learning Data Engineering skills and Big Data technologies.
  -
  - ğŸ’Œ Also reach me at my personal email kdpham1002@gmail.com

show_downloads: true
theme: jekyll-theme-minimal